// ------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja środowiska uruchomieniowego: 15.0.0.0
//  
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Pattern.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ClassTemplate : ClassTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("namespace ");
            
            #line 8 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classParameters.Namespace));
            
            #line default
            #line hidden
            this.Write(" {\r\n{\r\n   public class ");
            
            #line 10 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classParameters.ClassName));
            
            #line default
            #line hidden
            
            #line 10 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
if(!String.IsNullOrEmpty(classParameters.BaseClassName)){
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 10 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classParameters.BaseClassName));
            
            #line default
            #line hidden
            
            #line 10 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("{\r\n   ");
            
            #line 11 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
for(int i=0; i<classParameters.Parameters.Count;i++){
            
            #line default
            #line hidden
            this.Write("\t ");
            
            #line 12 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
if(!String.IsNullOrEmpty(classParameters.Parameters[i].AccessModifier)){
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classParameters.Parameters[i].AccessModifier));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 12 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classParameters.Parameters[i].ParameterType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 12 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classParameters.Parameters[i].ParameterName));
            
            #line default
            #line hidden
            this.Write(";\r\n   ");
            
            #line 13 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
 ;}
            
            #line default
            #line hidden
            this.Write("\r\n   ");
            
            #line 15 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
for(int i=0; i<methods.Count;i++){
            
            #line default
            #line hidden
            this.Write("\t ");
            
            #line 16 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
if(!String.IsNullOrEmpty(methods[i].AccessModifier)){
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methods[i].AccessModifier));
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 16 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methods[i].ReturnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 16 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methods[i].MethodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 16 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
if(methods[i].Parameters!=null)for(int j=0; j < methods[i].Parameters.Count;j++){
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methods[i].Parameters[j].ParameterType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 16 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methods[i].Parameters[j].ParameterName));
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(");\r\n   ");
            
            #line 18 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"
 ;}
            
            #line default
            #line hidden
            this.Write("   }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\Admin\source\repos\Pattern\Pattern\Template\ClassTemplate.tt"

private global::System.Collections.Generic.List<Pattern.Model.Method> _methodsField;

/// <summary>
/// Access the methods parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<Pattern.Model.Method> methods
{
    get
    {
        return this._methodsField;
    }
}

private global::Pattern.Model.ClassData _classParametersField;

/// <summary>
/// Access the classParameters parameter of the template.
/// </summary>
private global::Pattern.Model.ClassData classParameters
{
    get
    {
        return this._classParametersField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool methodsValueAcquired = false;
if (this.Session.ContainsKey("methods"))
{
    this._methodsField = ((global::System.Collections.Generic.List<Pattern.Model.Method>)(this.Session["methods"]));
    methodsValueAcquired = true;
}
if ((methodsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("methods");
    if ((data != null))
    {
        this._methodsField = ((global::System.Collections.Generic.List<Pattern.Model.Method>)(data));
    }
}
bool classParametersValueAcquired = false;
if (this.Session.ContainsKey("classParameters"))
{
    this._classParametersField = ((global::Pattern.Model.ClassData)(this.Session["classParameters"]));
    classParametersValueAcquired = true;
}
if ((classParametersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("classParameters");
    if ((data != null))
    {
        this._classParametersField = ((global::Pattern.Model.ClassData)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ClassTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
